name: Deploy to Firebase on merge to main (dev)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    env:
      VITE_FIREBASE_API_KEY: "${{ secrets.API_KEY }}"
      VITE_FIREBASE_AUTH_DOMAIN: "${{ secrets.AUTH_DOMAIN }}"
      VITE_FIREBASE_DATABASE_URL: "${{ secrets.DATABASE_URL }}"
      VITE_FIREBASE_PROJECT_ID: "${{ secrets.PROJECT_ID }}"
      VITE_FIREBASE_STORAGE_BUCKET: "${{ secrets.STORAGE_BUCKET }}"
      VITE_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.MESSAGING_SENDER_ID }}"
      VITE_FIREBASE_APP_ID: "${{ secrets.APP_ID }}"
      VITE_FIREBASE_MEASUREMENT_ID: "${{ secrets.MEASUREMENT_ID }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create Production Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: development
          path: build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase use dev
          firebase deploy --only hosting:dev
